name: fsvfhi
channels:
  - conda-forge
dependencies:
  - r-base=4.3
  - r-essentials
  - r-sf
  - r-terra
  - r-raster
  - r-exactextractr
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-ggplot2
  - r-tmap
  - r-classint
  - r-units
  - r-jupyter
  - r-irkernel
  - r-osmdata
  - r-httr
  - r-jsonlite
  - r-xml2
  - r-rvest
  - gdal
  - geos
  - proj
